version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  # Mapea el puerto 5000 del contenedor al puerto 5000 de tu máquina
    environment:
      - PYTHONUNBUFFERED=1  # Evita el almacenamiento en búfer de salida para depuración
      - PORT=5000           # Define el puerto para que Render lo detecte
    deploy:
      resources:
        limits:
          memory: 4g  # Limita el contenedor a 2 GB de RAM para evitar problemas de memoria
